### PR TITLE
Refactor build.rs to reduce duplicate code

### PR DESCRIPTION
**Pull request by mwilliammyers**
Hopefully this will make it easier to add new APIs going forward.

In the future it might be nice to explore using the artman/YAML config files or otherwise automatically determine the list of proto files.

### CODE REVIEW

**Comment by Hirevo** [comment]
I've made some changes to bring the CI more up-to-date and the tests are passing on master but the new CI configuration doesn't seem to be picked by just re-running the jobs of this PR.  
You may need to rebase this branch onto the latest master or merge the master branch into this branch.  
I don't know if I can do that myself since it is your fork.  
In the worst case, we could still merge the PR without the tests passing, see if it passes on master, and fix it in another PR if it still doesn't (at least, the new PR would be using the new CI config).

**Comment by mwilliammyers** [comment]
Hmmm I rebased my branch on top of master and now it looks like I am getting a real error. I will investigate it, but as far as I can tell I haven't changed the logic in `build.rs` (except for creating the directory first if it does not exist yet).

**Comment by Hirevo** [comment]
Sorry for the delay.  

It seemed weird to me as well, the PR passed the tests on my machine and after some digging I found that [GitHub Actions actually does not pass any secrets to runners assigned to PRs from a forked repository](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow) for security reasons, else anybody would have been able to log the secrets by submitting a PR.  
That reason is fair, and I don't know how to run tests in a way that mitigates this.  
But I think we can just merge this PR (it's pretty clear it works already) and let the tests run on master.

Thanks again for the PR !

**Comment by Hirevo** [comment]
The tests on master passed indeed ! :tada:

**Comment by mwilliammyers** [comment]
Ahhh. That’s good to know! Makes sense. 

Thanks!

**Pull request merged**
